sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-070
env:
  global:
    -
      # LTD_AWS_ID
      secure: GP0k2L+IX3seK9NcHlMDelxE28WX1EGBJkQXNJdYuDkAg93fudADNgCkcIaaaQZ/8o1O0159YtCZvMiza5ye+ylPFmcCm/6kqh0UuYfypxK3p1tvZ5jyZp0SBq8j3ztKNuwOMrPavqdSkhk19n9ZK9FBlD4Ciq8knwMbseFjdhxcTEsx/aZlCU6L4djUgL7n0ExjCzyjw4/5mYPqbpi/Bwiev3raRQ49SF7/WrazfRXwnvzo72q5Rm8WlufJHmB5g9T00h/q1ygN5HaYnhUv4KImPUqsSWuggE4J43I6NyDzBa8S6nJpl++w1Jfum6Z67V69aZ37O1K356QzH8B5UCr7u11uyibTbssyjkLLSMiqYBfrxAQ/OTcKEvR5SOnPN5QckVX5OS2mqx8z0yQELzEvp8FXK91fPnTupRKBjutkMzi3/4ueDV+g4f2kGprFwZhDgVrPl3oZ3ypqN+uUz0C1l9TcaQ9x1a6s6HNVwrO/BxMV5ytLpt4Nrie8jgoVPRElKaMXoSXy4LwNlrhdXBnONswMz8wXDROHqkxjnqWXDTBOX6sRLyR7ASGkOllVS1aeRENdu0MYHj4L87wdktgUiaRjZpKeOe0pNUFtXqieKzwef7MxSS99FrKNoNRg+TDM6+dgHX4/pfuSUt8O9143Haa2xGnpsebzJfpKZ/U=
    -
      # LTD_AWS_SECRET
      secure: kM2xnoeu7RO8mQYe5Ck++AcRbTyMF+TTBxHDFCNijuUY19NjynJq9X4q4tqnMhDTR4z4fPHdYQtEAm+C+soi3gnpksXAoudIxBjUAlRDTqJYtpNf2yUg/KOazRGgCgUC+lRxL2sl+tsy+V5iJfYUY3Tje0HnjGt/SwWhPyvbG7FQrOSBjnNhZRZJFQoKJYMsMZWHKzClOAtxr0Gyt9akYhWYaPIbj6wdmuh6+O8A3hw9TXNFyWu7bj/vxqIdVTxtW6q2KUaSFO1bHw5LZrb+HP/fALAsXLFAF1ktSab2O8OhN6LBbsGyFpbyql0opeXd6jGM7JHOAbwlRY4zS6q+sxYwlHJlRT2GE8Np9bz1aC/JBYKaCF8KdpgUb7bPXMOG39E/J0B4/JKhuyORy44PhgnbC5XkdpwYt7QDpsA+KaF8iMm7H7lm8et4L9X/8YUcP+1/NdMm4mxzJrab/upGDIIlVDiOn5x8asqlG+kvF7y/sdrcBBMwgBD8sor+qE7I9Fh9GLsSTVHsmYOeZj9xZ5epiX7mx2RtIqM9bKr4QdunHkilaWgCtjC8bjB4RVd/GNhmSQ0h7aERYG8OLHKCnbj6/MzHZt/SPPPFCeQDutC59VQdqP4hFGlMOn8LCW41H1DKP2WSpLHCmCaJjxsC+v1wfKneLYlUGngdXxvvsy0=
    -
      # LTD_USERNAME
      secure: VyVeDhx6J4rMq9yEUtiBM/zrNdmHwSo6hP33/dzAqWdXgt6Q/Bq5GHOgxPBPmabfx/plWIYWwo1AcqJoRxlq4kF3HVR+SWB860H6wepAuW7GeLaUfO0Y/sMLHJPiFEIJge9AJN1H7mWTG55rEa/G1MULVbXtPWKIc1Vk+BoEvaoLd9/y8ul69VHmKrVHhTz2nHPb/Nwcj/Sxy1EswEdKUQ+c7Mla8GUG0a5vbM/A7DB+jAyag4HN+5iSUez0ha/RX+sWohYq4p6aNwivP47+fBb77DWh07vjLomUvKYd3mhOoQbXCoUTi1K1UWSD9gHldzNVT17uWqTV86UZTB3tr+EHk1iLiDj/WvnGRe0LUe1qXpD+GSHhMAxmCmW0gAUYm3wGjqDsS9fE86I8xE9qYFujJQnLkgJ/AVUidVX2/2NdXgIUfG/0xhVJlBbPxnqpeNPJ/EDv72WdgYoPKb+5U+kPnlQCu63iAQqgvsK+stI+saf8uXaXmxzW+K4zYU0VPrz6TgiV2nR3u72jTwN7AlaxBA7MpCYcNdap+WIXHEZmI/e6qr5I177ba2YcoKmgqB+cRcvqaFM8vz9udhyMDYJXNdRDXwQj+dqQqkzYfOMgR4iKj/tCjaPleoxaenROKE7C0NhrOEV7+8Kei4wH+hTPAPrF065lyJajTkN0uzI=
    -
      # LTD_PASSWORD
      secure: O7FrdNO1GnKRgTnilB12OLP381HRp9MVvaycjckU0jFZkkTG6uP+Qz+DHoIn8RtwGWkJ0kSmQeyDepRpok8rxVl8LjPtWUVJTRcPWalZ2TLZ0ZrZAseuw3DehIU5Y6vZk0ysr/ewpAGMR2z0+ez//LTZuzIxe0kLWjTfnTuMsboiN27ls6yokjl68BspRaLtltXjPSMUb1VG7wu4UCi+pV7r0IGHOlMI4RjuMA4xoUbh2rYVU+LPke9+ZAsECzURJ9ZBCtdUOWtMoZ48RqP4a7GlkksgGn3Llmyr6kOJYu8HczjlPSq2dvmrOabqRGZp6gEWIM7PEs3LIa9Lw1ec1aGV92q0ZvzBlk5jZ9kPA0njmVg5/CdzQb6D3Vt1htOsMUXeS21IlYkx5yFRZD3oODxBsQfze91Ex/JWmFdffMpcyfN6CTB08w8+sreZMkMAm6H5fu9+zJVtxfN/fuXcjOHxrMWxGvBTVmKqBg11W8Ev7Qc8DUXWJKyVG+58D8br7EP24vUT4i2Ynfh76FYoKKTjQ3GVfH4+bUFkHbEvHY3GxAIzlwN+1HxJ9fgS672CguF3XI6PkqnVAANoosJLB7fHiDSPCOdK+jdsbZ2ETFbR2FQ4annDe567DBYYa7wTktoQLRlXpdRLj0aNyoyaTyhg+ZvdyumuQiy3odIVM4c=
